### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by ChthonVII** [sergiodias25/Snap_Player_Stats#1]
Doesn't work for Linux desktop users (running the desktop version via wine). In order to get it working, I believe two things are needed:
1. Distinguish "Linux" from "Android" so that it doesn't try to use the android-specific behavior.
2. The path for wine should be ~/.steam/steam/steamapps/compatdata/1997040/pfx/drive_c/users/steamuser/... instead of ~/...

**Comment by sergiodias25** [comment]
What error did you get?
When I run this on Android it outputs the os as "Linux" so I'm not sure what is the solution here, but I'll look into it.

**Comment by sergiodias25** [comment]
Just pushed a commit with an improvement for your issues.
Not sure it solves issue 2 but let me know!

**Comment by ChthonVII** [comment]
It works if you fix the typos. See my pull request.

**Comment by sergiodias25** [comment]
I merged you changes and then did a little update to prevent the linux code from overriding the Android settings.
Thanks for your help!
